#!/usr/bin/env python2

import sys
import yaml

from twisted.words.protocols import irc
from twisted.internet import protocol, reactor

from hamper.commander import CommanderFactory
from hamper import log


if __name__ == '__main__':

    config = yaml.load(open('hamper.conf'))
    log.setup_logging()

    for key in ['server', 'port', 'nickname', 'channels']:
        if (key not in config) or (not config[key]):
            print('You need to define {0} in the config file.'.format(key))
            sys.exit();

    reactor.connectTCP(config['server'], config['port'],
            CommanderFactory(config))
    reactor.run()
